name: waterbot_flutter
description: Flutter app version of Arizona Water Chatbot
publish_to: 'none'
environment:
   sdk: '>=3.4.0 <4.0.0'
dependencies:
   flutter:
     sdk: flutter
   http: ^1.2.2
   web_socket_channel: ^2.4.5
   url_launcher: ^6.3.0
   intl: ^0.19.0
   provider: ^6.1.2
   flutter_markdown: ^0.7.4+7
dev_dependencies:
   flutter_test:
     sdk: flutter
   flutter_lints: ^4.0.0
flutter:
   uses-material-design: true
   assets:
      - assets/images/WaterDrop1.png
      - assets/images/background.png

